# File: netlify.toml

# Konfigurasi Build
[build]
  command = "npm run build"
  publish = "dist"

# Aturan Redirect untuk Single Page Application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# PENTING: Aturan Header untuk memperbaiki masalah MIME type
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"